name: mandatory tests macos

on:
  push:
    branches: [ "validated" ]
  pull_request:
    branches: [ "validated" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: mandatory tests
      run: cd ./ft_container/tester/; ./do.sh
      shell: bash
